camera:
  width: 1280  # Higher resolution for better accuracy
  height: 720
  fps: 24     # Lower FPS for better stability
  buffer_size: 1  # Reduced buffer size
  exposure: -4    # Better exposure control
  brightness: 128 # Middle range brightness
  contrast: 128   # Middle range contrast
  saturation: 128 # Middle range saturation
  gain: 0        # Auto gain control
  white_balance: 4000  # Custom white balance
  autofocus: true  # Enable autofocus
  autoexposure: true  # Enable autoexposure
  autogain: true    # Enable autogain

face_detection:
  scale_factor: 1.1
  min_neighbors: 5
  resize_dimensions: [150, 150]
  confidence_threshold: 75

color_detection:
  min_pixels_threshold: 100
  detection_region: [1/3, 2/3]
  colors:
    red:
      ranges: [[0, 150, 50], [10, 255, 255], [170, 150, 50], [180, 255, 255]]
      bgr: [0, 0, 255]
    green:
      ranges: [[35, 80, 50], [85, 255, 255]]
      bgr: [0, 255, 0]
    blue:
      ranges: [[90, 100, 50], [130, 255, 255]]
      bgr: [255, 0, 0]
    yellow:
      ranges: [[20, 100, 50], [35, 255, 255]]
      bgr: [0, 255, 255]

object_detection:
  confidence_threshold: 0.5
  detection_interval: 1.0
  input_size: 416

models:
  face_recognizer: "D:\\project\\pythonProject1\\faces_recognizer999.xml"
  label_map: "D:\\project\\pythonProject1\\label_map999.npy"
  face_cascade: "haarcascade_frontalface_default.xml"
